import "./globals.css";

import { Header } from "./components/header";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import { Providers } from "../providers/providers";
import { Toaster } from "@machines/ui";
import { cn } from "@machines/ui/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren<{}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={cn(inter.className, "flex flex-col w-full min-h-screen")}
        >
          <Header />
          <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] bg-gray-100/40 flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10 dark:bg-gray-800/40">
            {children}
          </main>
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
